Backend/cart/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from .import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('add/(<int:product_id>', views.cart_add, name='cart_add'),
    path('create/', views.order_create, name='order_create'),
    path('checkout/',views.checkout, name='checkout'),
    path('success/',csrf_exempt(views.success)),
]

Backend/panda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('customer/', include('customers.urls')),
    path('seller/', include('sellers.urls')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/cart/models.py
from django.db import models
from accounts.models import Customer, User
from products.models import Product

# Create your models here.

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    email = models.EmailField(null=True)
    address = models.CharField(max_length=250 , null=True)
    city = models.CharField(max_length=100, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, related_name='order_items')
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

Backend/cart/forms.py
from django import forms
from .models import Order,OrderItem

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
        quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
        update = forms.BooleanField(required=False,
        initial=False,
        widget=forms.HiddenInput)

class OrderCreateForm(forms.ModelForm):
   class Meta:
        model = Order
        fields = ['email', 'address', 'city']

Backend/cart/views.py
from django.shortcuts import render
from sslcommerz_lib import SSLCOMMERZ
from django.http import JsonResponse
from .models import Order, OrderItem
from products.models import Product
import json
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from products.models import Product
from accounts.models import Customer, User, Seller
from .cart import Cart
from .forms import CartAddProductForm
from django.views.decorators.csrf import ensure_csrf_cookie
import uuid
#import pycurl 
@login_required
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
        quantity=cd['quantity'],
        update_quantity=cd['update'])
        return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})
    return render(request, 'cart/cart.html', {'cart': cart})

def order_create(request):
    customer = Customer.objects.get(user_id=request.user)
    cart = Cart(request)
    order = Order.objects.create(customer=customer, email=customer.email, address=customer.address, paid=True)
    for item in cart:
        OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])

    cart.clear()
    return render(request,'cart/cart.html',{'order': order})
    
@ensure_csrf_cookie
def checkout(request):
    cart = Cart(request)
    customer = Customer.objects.get(user_id=request.user)
    settings = { 'store_id': 'bookr5f41517d60625', 'store_pass': 'bookr5f41517d60625@ssl', 'issandbox': True }
    sslcommez = SSLCOMMERZ(settings)
    post_body = {}
    post_body['total_amount'] = cart.get_total_price()
    post_body['currency'] = "BDT"
    post_body['tran_id'] = '5E121A0D01F92'
    post_body['success_url'] = "http://127.0.0.1:8000/cart/success/"
    post_body['fail_url'] = "your fail url"
    post_body['cancel_url'] = "your cancel url"
    post_body['emi_option'] = 0
    post_body['cus_name'] = "request.user"
    post_body['cus_email'] = customer.email
    post_body['cus_phone'] = customer.phone_number
    post_body['cus_add1'] = customer.address
    post_body['cus_city'] = "Dhaka"
    post_body['cus_country'] = "Bangladesh"
    post_body['shipping_method'] = "NO"
    post_body['multi_card_name'] = ""
    post_body['num_of_item'] = 1
    post_body['product_name'] = "Test"
    post_body['product_category'] = "Test Category"
    post_body['product_profile'] = "general"
    response = sslcommez.createSession(post_body)
    return redirect(response['GatewayPageURL'])


def success(request):
    settings = { 'store_id': 'bookr5f41517d60625', 'store_pass': 'bookr5f41517d60625@ssl', 'issandbox': True }
    sslcommez = SSLCOMMERZ(settings)
    tranid = '59C2A4F6432F8'
    response = sslcommez.transaction_query_tranid(tranid)
    context={
        "response":response,
    }
    cart = Cart(request)
    cart.clear()
    return render(request,'cart/checkout.html', context)

Backend/templates/cart/cart.html
{% load static %}
{% load widget_tweaks %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link rel="stylesheet" href="{% static 'css/cart.css'%}">
    <script type="text/javascript">
      var user = '{{request.user}}';
      
      function get_token(name){
        var cookieValue = null;
        if(document.cookie && document.cookie!==''){
          var cookies = document.cookie.split(';');
          for(var i=0; i<cookies.length;i++){
              var cookie = cookies[i].trim();
              if(cookie.substring(0, name.length+1) === (name + '=')){
                 cookieValue = decodeURIComponent(cookie.substring(name.length+1));
                 break;
              }
          }
        }
        return cookieValue;
      }
      var csrftoken = get_token('csrftoken');
    </script>
</head>
<body>
<!----------------------Navbar--------------------------->
<header>
    <nav class="navbar navbar-expand-sm">
        <!-- Brand/logo -->
        <div class="nav-logo">
            <a href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}"</a>
        </div>
        <!-- Links -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"><i class="fa fa-bars"></i>
          </span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">

          {% if user.is_authenticated and user.is_seller%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'seller_dashboard' %}">Seller dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
          {% else %}
               
              {% if user.is_authenticated and user.is_customer %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer_dashboard' %}">Account</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'seller_register' %}">Become a Seller</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Browse Products</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="">My Cart</a>
                  </li>
              {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'seller_register' %}">Become a Seller</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Browse Products</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer_register' %}">Sign up</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_page' %}">Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="">My Cart</a>
                  </li>
              {% endif %}
          {% endif %}
        </ul>
        </div>
    </nav>
</header>

<body>

      <div class="container">
         <div class="cart">
            <div class="cart-align">
               <h3>Shopping Cart</h3>
            </div>
            {% for item in cart %}
            {% with product=item.product %}
            <div class="col-md-12 col-lg-10 mx-auto">
               <div class="cart-item">
                  <div class="row">
                     <div class="col-md-7 center-item">
                        <img src="{{product.image.url}}" alt="">
                        <h5>{{product.name}}</h5>
                     </div>

                     <div class="col-md-5 center-item">
                        <div class="input-group number-spinner">
                                   
                           <td>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Update">
                            {% csrf_token %}
                            </form>
                           </td>
                        </div>

                        <h5><span id = "iphonePrice">Tk.{{item.price}}</span></h5>
              
                        <h5> <span id = "iphonePrice">Tk.{{ item.total_price }}</span></h5>
                        <a href="{% url 'cart:cart_remove' product_id=product.id %}">Remove</a>
                        <img src="img/remove.png" alt="" class="remove-item">
                      </div>
                   </div>
                </div>
             {%endwith%}
             {%endfor%}
                       

           
               <div class="col-md-12 pt-4 pb-4">
                  <a href="{% url "cart:checkout" %}"><button type="button" class=" check-out">Check Out</button></a>
               </div>
            </div>
         </div>
      </div>
      {% if order %}
        <h1>Thank you</h1>
        <p>Your order has been successfully completed. Your order number is
      <strong>{{ order.id }}</strong>.</p>
      {%endif%}
      lass="col-md-4 footer-social">
             <a href="#"><i class="fa fa-facebook fa-social"></i></a>
             <a href="#"><i class="fa fa-twitter fa-social"></i></a>
             <a href="#"><i class="fa fa-instagram fa-social"></i></a>
          </div>
         </div>
         <div class="row">
           <div class="col-md-12">
           <div class="footer-copyright">
            <p>&copy<div class="footer">
         <div class="row">
           <div class="col-md-4">
              <a class="footer-font-color">About</a>
              <a class="footer-font-color">Trust &#38 Safety</a>
           </div>
           <div class="col-md-4">
            <a class="footer-font-color">Career</a>
            <a class="footer-font-color">Privacy & Terms</a>
          </div>
          <div c 2020 PANDA, Inc. All rights reserved </p>
          </div>
        </div>
         </div>
        </div>
      </footer>
     
   </body>
</html>
{% endblock %}

Backend/templates/cart/checkout.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css'%}">
</head>
<body>
<!----------------------Navbar--------------------------->
<header>
    <nav class="navbar navbar-expand-sm">
        <!-- Brand/logo -->
        <div class="nav-logo">
            <a href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}"</a>
        </div>
        <!-- Links -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"><i class="fa fa-bars"></i>
          </span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">

          {% if user.is_authenticated and user.is_seller%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'seller_dashboard' %}">Seller dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
          {% else %}
               
              {% if user.is_authenticated and user.is_customer %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer_dashboard' %}">Account</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'seller_register' %}">Become a Seller</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Browse Products</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}">My Cart</a>
                  </li>
              {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'seller_register' %}">Become a Seller</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Browse Products</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer_register' %}">Sign up</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_page' %}">Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}">My Cart</a>
                  </li>
              {% endif %}
          {% endif %}
        </ul>
        </div>
    </nav>
</header>

<section>
    <div class="container">
        <div class="row">
           <div class="col-md-1"></div>
           <div class="col-xs-12 col-sm-12 col-md-10">
              <div class="genre-list-table">
                  <table>
                      {% if response %}
                  <tr>
                      <td colspan="1">Total amount</td>
                      <td colspan="1">{{response.element.0.currency_amount}}</td>
                  </tr>
                  <tr>
                      <td colspan="1">Transaction Date</td>
                      <td colspan="1">{{response.element.0.tran_date}}</td>
                  </tr>
                  <tr>
                      <td colspan="1">Transaction ID</td>
                      <td>{{response.element.0.tran_id}}</td>
                  </tr>
                  <tr>
                      <td colspan="1">Phone Number</td>
                      <td></td>
                      {% endif %}
                  </tr>
                  </table>
              </div>
           </div>
           <div class="col-md-1"></div>
        </div>
    </div>
</section>
<br><br><br><br><br>

<div class="footer">
    <div class="row">
      <div class="col-md-4">
         <a class="footer-font-color">About</a>
         <a class="footer-font-color">Trust &#38 Safety</a>
      </div>
      <div class="col-md-4">
       <a class="footer-font-color">Career</a>
       <a class="footer-font-color">Privacy & Terms</a>
     </div>
     <div class="col-md-4 footer-social">
        <a href="#"><i class="fa fa-facebook fa-social"></i></a>
        <a href="#"><i class="fa fa-twitter fa-social"></i></a>
        <a href="#"><i class="fa fa-instagram fa-social"></i></a>
     </div>
    </div>
    <div class="row">
      <div class="col-md-12">
      <div class="footer-copyright">
       <p>&copy 2020 PANDA, Inc. All rights reserved </p>
     </div>
   </div>
    </div>
   </div>
 </footer>
 
{% endblock %}