Backend/cart/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from .import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('add/(<int:product_id>', views.cart_add, name='cart_add'),
    path('create/', views.order_create, name='order_create'),
    path('checkout/',views.checkout, name='checkout'),
    path('success/',csrf_exempt(views.success)),
]

Backend/panda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('customer/', include('customers.urls')),
    path('seller/', include('sellers.urls')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/products/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('product_list/', views.products, name='products'),
    path('<str:cat>/product_category/', views.product_category, name='product_category'),
    path('<int:pk>/single_product/<str:token>/', views.single_product, name='single_product'),
    #path('<str:token>/single_product/', views.single_product, name='single_product'),
    path('custom_search/', views.custom_search, name='custom_search'),
    #path('<int:pk>/review/', views.add_review, name='add_review'),
]

Backend/products/models.py
from django.db import models
from django.utils import timezone
from datetime import date
from taggit.managers import TaggableManager
from accounts.models import Seller, User, Customer

class Product(models.Model):
    CATEGORY = (
                 ('Phones & Accessories', 'Phones & Accessories'),
                 ('Kitchen Tools', 'Kitchen Tools'),
                 ('Baby Products', 'Baby Products'),
                 ('Women\'s Clothing', 'Women\'s Clothing'),
                 ('Men\'s Clothing', 'Men\'s Clothing'),
                 ('Beauty, Hair & Health', 'Beauty, Hair & Health'),
                 ('Shoes','Shoes'),
                 ('Bags', 'Bags'),
                 ('Sports & Outdoors', 'Sports & Outdoors'),
                 ('Home Improvement Tools', 'Home Improvement Tools'),
                 ('Gadgets', 'Gadgets'),
               )
    seller = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="products")
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(null=True, decimal_places=2, max_digits=10)
    category = models.CharField(max_length=100, null=True, choices=CATEGORY)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to="gallery")
    uploaded_at = models.DateTimeField(default=timezone.now, null=True)
    total_units = models.IntegerField(default=1)
    tags = TaggableManager()

    class Meta:
        db_table = 'Product'
        verbose_name = "product"

    def __str__(self):
        return self.name

class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name="reviews")
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="user_review")
    text = models.TextField()
    added_at = models.DateTimeField(default=timezone.now, null=True)

    class Meta:
        db_table = 'Review'
        verbose_name = "review"

    def __str__(self):
        return self.product


'''class Order(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    name = models.ForeignKey(Seller, on_delete=models.CASCADE)
    price = models.DecimalField(null=True, decimal_places=2, max_digits=10)
    category = models.CharField(max_length=100, null=True, choices=CATEGORY)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to="gallery")'''

Backend/products/forms.py
from django import forms
from django.utils import timezone
from datetime import date
from products.models import Product,Review

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('text',)

Backend/products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Review
from accounts.models import User
from customers.models import Wish_list, Favourite
from .forms import ReviewForm
from django.http import HttpResponseRedirect
from cart.forms import CartAddProductForm

# Create your views here.

def products(request):
    products = Product.objects.all()
    context={
        'products': products,
    }
    return render(request, 'products/products.html', context)

def product_category(request, cat):
    products = Product.objects.filter(category__iexact=cat)
    context={
        'products': products,
    }
    return render(request, 'products/products.html',context)

def custom_search(request):

    if request.method == 'GET':
        category = request.GET['category'] 
        min_price = request.GET.get('min', 0)
        max_price = request.GET.get('max', 0)
        product = Product.objects.filter(category__iexact=category)
        product =product.filter(price__range=(min_price, max_price))
    context= {
        'product' : product,
    }

    return render(request, 'products/products.html', context)


def single_product(request, pk=None, token=None):
    product = get_object_or_404(Product, pk=pk)
    #product = Product.objects.get(id=pk)
    reviews = product.reviews.all()
    cart_product_form = CartAddProductForm()
    if request.user.id is not None:
       user = get_object_or_404(User, id=request.user.id)
       #if user presses wish list button
       if token == 'wish':
           wish = Wish_list(product=product, customer=user)
           wish.save()
           form = ReviewForm()
           context={
                    'product': product,
                    'form': form,
                    'reviews':reviews,
                    'cart_product_form': cart_product_form,
                }
           return render(request, '../templates/products/single_product.html',context)
       if token == 'favourite':
           favourite = Favourite(product=product, customer=user)
           favourite.save()
           form = ReviewForm()
           context={
                    'product': product,
                    'form': form,
                    'reviews':reviews,
                    'cart_product_form': cart_product_form,
                }
           return render(request, '../templates/products/single_product.html',context)
       if request.method == "POST":
            form = ReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.product = product
                review.customer = user
                review.save()
                reviews = product.reviews.all()
                form = ReviewForm()
                context={
                        'product': product,
                        'form': form,
                        'reviews':reviews,
                        'cart_product_form': cart_product_form,
                    }
                return render(request, '../templates/products/single_product.html',context)
       else:
            form = ReviewForm()
       context={
            'product': product,
            'form': form,
            'reviews':reviews,
            'cart_product_form': cart_product_form,
        }
       return render(request, '../templates/products/single_product.html',context)
    context={
            'product': product,
            'reviews':reviews,
            'cart_product_form': cart_product_form,
        }
    return render(request, '../templates/products/single_product.html',context)

'''def add_review(request, pk):
    user = get_object_or_404(User, id=request.user.id)
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.product = pk
            review.customer = user
            product.save()
            return redirect('../templates/products/single_product.html')
    else:
        form = ReviewForm()

    return render(request, '../templates/products/single_product.html',{'form': form})'''


'''customer = User.objects.filter(id=pk)
    reviews = Review.objects.all()
    user_review = Product.user_review.all()
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.customer = user
            review.product = product
            review.save()
            return redirect('../templates/products/single_product.html')
    else:
        form = ReviewForm()
    context={
        'product': product,
        'form'   :form,
        'reviews' : reviews,
    }'''

Backend/templates/products/products.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>
<body>
<!----------------------Navbar--------------------------->
<header>
    <nav class="navbar navbar-expand-sm">
        <!-- Brand/logo -->
        <div class="nav-logo">
            <a href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}"</a>
        </div>
        <!-- Links -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"><i class="fa fa-bars"></i>
          </span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">

          {% if user.is_authenticated and user.is_seller%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'seller_dashboard' %}">Seller dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
          {% else %}
               
              {% if user.is_authenticated and user.is_customer %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer_dashboard' %}">Account</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'seller_register' %}">Become a Seller</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Browse Products</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}">My Cart</a>
                  </li>
              {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'seller_register' %}">Become a Seller</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Browse Products</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer_register' %}">Sign up</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_page' %}">Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}">My Cart</a>
                  </li>
              {% endif %}
          {% endif %}
        </ul>
        </div>
    </nav>
</header>
   
    <!----------------------Search Item--------------------------->
    <!--<section>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-xs-12 col-sm-12 col-md-6  category-border-length">
               <div class="product-search">
                <form  action="/">
                  <input type="text" placeholder="black T-shirt" name="search">
                  <button type="submit">Search</button>
                </form>
               </div>
            </div>
            <div class="col-md-3"></div>
         </div>
    </section>-->

    <!----------------------Product Category List--------------------------->
    <section>
        <div class="container-fluid">
           <div class="row">
             <div class="col-md-3 col-xs-12 col-sm-12">
               <div>
                <table class="category-table" border="1">
                  <tr>
                    <th>Categories</th>
                  </tr>
                  <tr >
                    <td><a href="{% url 'product_category' cat='Phones & Accessories' %}"><img src="{% static 'icons/mobile.png' %}"> Phones & Accessories</a> </td>
                  </tr>
                  <tr>
                    <td><a href="{% url 'product_category' cat=' Kitchen Tools' %}"><img src="{% static 'icons/knife.png' %}"> Kitchen Tools</a> </td>
                  </tr>
                  <tr>
                    <td><a href="{% url 'product_category' cat='Baby Products' %}"><img src="{% static 'icons/baby bottle.png' %}">  Baby Products</a> </td>
                  </tr>
                  <tr>
                    <td><a href="{% url 'product_category' cat='Women\'s Clothing' %}"><img src="{% static 'icons/dress.png' %}">  Women's Clothing</a> </td>
                  </tr>
                  <tr>
                    <td><a href="{% url 'product_category' cat='Men\'s Clothing' %}"><img src="{% static 'icons/men shirt.png' %}">  Men's Clothing</a> </td>
                  </tr>
                  <tr>
                    <td><a href="{% url 'product_category' cat='Beauty, Hair & Health' %}"><img src="{% static 'icons/lipstick.png' %}">  Beauty, Hair & Health</a> </td>
                  </tr>
                  <tr>
                    <td><a href="{% url 'product_category' cat='Shoes' %}"><img src="{% static 'cons/shoe.png' %}">  Shoes</a> </td>
                  </tr>
                  <tr>
                    <td><a href="{% url 'product_category' cat='Bags' %}"><img src="{% static 'icons/bag.png' %}">  Bags</a> </td>
                  </tr>
                  <tr>
                    <td><a href="{% url 'product_category' cat='Sports & Outdoors' %}"><img src="{% static 'icons/ball.png' %}"> Sports & Outdoors</a> </td>
                  </tr>
                  <tr>
                    <td><a href="{% url 'product_category' cat='Home Improvement Tools' %}"><img src="{% static 'icons/game.png' %}"> Home Improvement Tools</a> </td>
                  </tr>
                  <tr>
                    <td><a href="{% url 'product_category' cat='Gadgets' %}"><img src="{% static 'icons/game.png' %}"> Gadgets</a> </td>
                  </tr>
                 
                </table>
               </div>
             </div>
             <div class="col-xs-12 col-sm-12 col-md-9">
               <div class="custom-search">
                  <form class="custom-search-form" action="{% url 'custom_search' %}" method="GET">
                    <div class="row">
                      <div clas="col-md-6 col-xl-6">
                        <label for="category-list">Category :</label>
                        <select name="category" id="">
                          <option value="Phones & Accessories"> Phones & Accessories</option>
                          <option value="Kitchen Tools"> Kitchen Tools</option>
                          <option value="Baby Products"> Baby Products</option>
                          <option value="Women's Clothing"> Women's Clothing</option>
                          <option value="Men's Clothing"> Men's Clothing</option>
                          <option value="Beauty, Hair & Health"> Beauty, Hair & Health</option>
                          <option value="Shoes"> Shoes</option>
                          <option value="Bags"> Bags</option>
                          <option value="Sports & Outdoors"> Sports & Outdoors</option>
                          <option value="Home Improvement Tools"> Home Improvement Tools</option>
                          <option value=" Gadgets"> Gadgets</option>
                        </select>
                      </div>
                      <div clas="col-md-6 col-xl-6">
                        <label for="category-list">Price :</label>
                        <input type="text" name="min" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" placeholder="Min"/><span> -</span>
                        <input type="text" name="max" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" placeholder="Max"/>
                      </div>
                    </div>

                   

                    <div class="row">
                      <div class="col-md-1"></div>
                      <div class="col-xs-12 col-sm-12 col-md-10  signup-input">
                       <input type="submit" value="Search">
                      </div>
                      <div class="col-md-1"></div>
                  </div>
                  </form>
               </div>
             
              <div class="product-list">
                {% if products %}
                  {% for product in products %}
                      <a href="{% url 'single_product' pk=product.pk token=0 %}">
                        <img src="{{product.image.url}}"/>
                        <p>{{product.name}} </p>
                        <p>Tk. {{product.price}}</p>
                      </a>
                  {% endfor %}                                                      
                {% else %}
                      {% if product %}
                      {% for prod in product %}
                          <a href="{% url 'single_product' pk=prod.pk token=0 %}">
                            <img src="{{prod.image.url}}"/>
                            <p>{{prod.name}} </p>
                            <p>Tk. {{prod.price}}</p>
                          </a>
                      {% endfor %}                                                      
                    {% else %}
                    <p>No products to show</p>
                    {% endif %}
                {% endif %}
             </div>

                <div class="pagination">
                  <a href="#">&laquo;</a>
                  <a href="#">1</a>
                  <a class="active" href="#">2</a>
                  <a href="#">3</a>
                  <a href="#">4</a>
                  <a href="#">5</a>
                  <a href="#">6</a>
                  <a href="#">&raquo;</a>
                  
                  </div>
            </div>
          </div>
            </div> 
    </div>                       
   </section>

    <!----------------------Footer---------------------------> 
    <footer>
      <div class="footer">
       <div class="row">
         <div class="col-md-4">
            <a>About</a>
            <a>Trust &#38 Safety</a>
         </div>
         <div class="col-md-4">
          <a>Career</a>
          <a>Privacy & Terms</a>
        </div>
        <div class="col-md-4 footer-social">
           <a href="#"><i class="fa fa-facebook fa-social"></i></a>
           <a href="#"><i class="fa fa-twitter fa-social"></i></a>
           <a href="#"><i class="fa fa-instagram fa-social"></i></a>
        </div>
       </div>
       <div class="row">
         <div class="col-md-12">
         <div class="footer-copyright">
          <p>&copy 2020 PANDA, Inc. All rights reserved </p>
        </div>
      </div>
       </div>
      </div>
    </footer>
</body>
</html>

{% endblock %}

Backend/templates/products/single_product.html
{% load static %}
{% load widget_tweaks %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <script type="text/javascript">
      var user = '{{request.user}}';
      
      function get_token(name){
        var cookieValue = null;
        if(document.cookie && document.cookie!==''){
          var cookies = document.cookie.split(';');
          for(var i=0; i<cookies.length;i++){
              var cookie = cookies[i].trim();
              if(cookie.substring(0, name.length+1) === (name + '=')){
                 cookieValue = decodeURIComponent(cookie.substring(name.length+1));
                 break;
              }
          }
        }
        return cookieValue;
      }
      var csrftoken = get_token('csrftoken');
    </script>
</head>
<body>
<!----------------------Navbar--------------------------->
<header>
    <nav class="navbar navbar-expand-sm">
        <!-- Brand/logo -->
        <div class="nav-logo">
            <a href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}"</a>
        </div>
        <!-- Links -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"><i class="fa fa-bars"></i>
          </span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">

          {% if user.is_authenticated and user.is_seller%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'seller_dashboard' %}">Seller dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
          {% else %}
               
              {% if user.is_authenticated and user.is_customer %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer_dashboard' %}">Account</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'seller_register' %}">Become a Seller</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Browse Products</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}">My Cart</a>
                  </li>
              {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'seller_register' %}">Become a Seller</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Browse Products</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer_register' %}">Sign up</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_page' %}">Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}">My Cart</a>
                  </li>
              {% endif %}
          {% endif %}
        </ul>
        </div>
    </nav>
</header>

    <div class="row">
        <div class="col span-2-of-2">
            <div class="back-button">
                <a href="#"><button>Go Back</button></a>
            </div>
        </div>
    </div>

     <!----------------------Product--------------------------->
    <section>
        <div class="container">
           <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-6">
                <div class="item-vid-img">
                 <div class="single-product-image">
                  
                      {% if product %}
                                <img src="{{product.image.url}}" alt=""/>
                                <div class="single-product-actions">
                                  <p><i class="fa fa-shopping-basket fa-black"></i><a href="{% url 'single_product' pk=product.pk token='wish' %}">Add to Wish list</a></p>
                                  <p><i class="fa fa-heart"></i><a href="{% url 'single_product' pk=product.pk token='favourite' %}">Add to Favourites</a></p>
                                </div>
                            </div>
                            <!---- <div>
                                <video width="400" height="240" controls>
                                    <source src="vid/unbox.mp4" type="video/mp4">
                                  Your browser does not support the video tag.
                                  </video> 
                            </div>-->
                          </div>
                        </div>
                          <div class="col-xs-12 col-sm-12 col-md-6">
                            <div class="product-heading">
                                <p>{{product.name}}</p>
                                <p>TK. {{product.price}}</p>
                                <i class="fa fa-star avg-star"></i><i class="fa fa-star avg-star"></i><i class="fa fa-star avg-star"></i><i class="fa fa-star hollow-star avg-star"></i><i class="fa fa-star hollow-star avg-star"></i><!--<p>(35)</p>-->
                            </div>
                            <div class="cart-button">
                              <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {{ cart_product_form }}
                                {% csrf_token %}
                                <input style="width:400px; border: 2px solid #000; background-color: #000; color: #fff;" type="submit" value="Add to cart">
                              </form>
                               
                            </div>
                               
                            <div class="container">
                                <div class="row">
                                    <div class="col-xs-12 col-sm-12 col-md-12 review-info-section">
                                        <div class="product-info-review">
                                          <a href="#"  onclick="item_info_page()">ITEM INFO</a>
                                          <a href="#"  onclick="review_page()">REVIEWS (20)</a>
                                        </div>
                                        <div class="product-description" id="item-info">
                                            <p>{{product.description}}</p>
                                        </div>
                      {% endif %}
                         
                            <div class="product-review" id="item-review">
                                <div class="write-review">
                                    <div class="rvw-star">
                                    <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i>
                                    </div>
                                  <form method="POST">
                                    {% csrf_token %}
                                          {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                          {% endfor %}
                            
                                          {% for field in form.visible_fields %}
                                              <div class="form-group">
                                                <label for="{{ field.id_for_label }}">{{ field.label }}</label><br>
                                                {% render_field field class="form-control" %}
                                                  {% for error in field.errors %}
                                                  <span class="help-block">{{ error }}</span>
                                                  
                                                {% endfor %}
                                            </div>
                                          {% endfor %}
                                    <input type="submit" value="Submit"><br><br>
                                  </form>
                                </div>
                                {% for review in product.reviews.all %}
                                <div class="reviews">
                                    <h6> </h6>
                                    <div class="rvw-star">
                                    <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star hollow-star"></i><i class="fa fa-star hollow-star"></i>
                                    </div>
                                    <p>{{ review.text }}</p>
                                </div>
                                {% empty %}
                                    <p>No comments here yet :(</p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           </div>
        </div>

        
    </section>
     
</body>

<script type="text/javascript" src="{% static 'scripts/single_product.js' %}" rel="stylesheet"></script>
</html>
{% endblock %}